### ISSUE TITLE
有些内容还没有汉化

### ISSUE THREAD

**Issue by hetangx** [wangweixuan/vscode-zh-hans-custom#1]
![image](https://user-images.githubusercontent.com/33305171/76975818-105beb80-696e-11ea-8ef5-2117efd9c507.png)

**Comment by wangweixuan** [comment]
感谢您的支持！今天会发布更新。

**Comment by wangweixuan** [comment]
更新已发布，添加了 VS Code 1.43 版本的完整支持。
